<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amount_discount</name>
   <tag></tag>
   <elementGuidId>cfb1607b-3d5d-4645-a353-27e7a4eab441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[3]/div/div/div/form/div[1]/div/div[1]/div[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[3]/div/div/div/form/div[1]/div/div[1]/div[2]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
