<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_00_Positive</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>2</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d87c5999-219b-4826-8f36-9c6453bcd9d8</testSuiteGuid>
   <testCaseLink>
      <guid>905b33ee-954c-4730-8d5b-3f5acccaa9a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO01_Navigate to url</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9797d877-a69c-493d-9d4f-659bbc8ad1b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO02_Add to cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>306a035f-d3ec-4b7e-bc95-44c4445cb68c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO03_Checkout process</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d008e4c-c518-4b7c-a95f-2c6e1b514f23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa9e5a2b-3f72-4b23-b160-98085299a975</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2682158-70d7-43b0-aff1-d5668aedbeed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d34a69a-3610-48c1-bee1-cee73ca9e186</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0da3c769-c841-41f4-b905-36d1103d41b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95f0e84f-4ee3-4f4b-a35f-939457e66bdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae7388d6-5ea0-49ac-bd3d-f5e2c04f964e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO04_Order summary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d51726ac-38a0-4587-8f6e-9ff146d988b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfbcce2a-19dd-4eb9-8be1-dbe0e904b4b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO05_Payment process</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea826c5e-d353-45e4-ae75-058edf3c6bc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>465a64e8-db45-4d1e-833b-5936b3cc443b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91ca2a10-4c38-4d1a-ada5-c147eaed98ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>724d033c-928c-4717-8b59-f4c3b58b8221</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
