<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_01_Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>2</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b334b062-2a82-47e9-92da-42737502d35c</testSuiteGuid>
   <testCaseLink>
      <guid>ad163d53-3cb1-449f-a9a9-3a0800e72b38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO01_Navigate to url</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>59cd6b90-adaa-4cfd-8b47-59e1057303f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO02_Add to cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b0072e84-c896-40fc-85d8-683e68466e82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO03_Checkout process</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d008e4c-c518-4b7c-a95f-2c6e1b514f23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa9e5a2b-3f72-4b23-b160-98085299a975</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2682158-70d7-43b0-aff1-d5668aedbeed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d34a69a-3610-48c1-bee1-cee73ca9e186</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0da3c769-c841-41f4-b905-36d1103d41b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95f0e84f-4ee3-4f4b-a35f-939457e66bdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4053a9b-a2f4-4319-939f-e6b1a4843923</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO04_Order summary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d51726ac-38a0-4587-8f6e-9ff146d988b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecb47704-e656-4aef-ba92-caf096af4aff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO06_Payment using invalid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2a6e1319-76f5-4612-b852-736832911bfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO07_Change price</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f7108f39-27fd-4785-bd05-fd659fb96ddc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/CO09_Invalid customer data</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9a11072f-fa26-4a96-854a-eae0c9752943</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/Midtrans/Database Negative</testDataId>
      </testDataLink>
   </testCaseLink>
</TestSuiteEntity>
