<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>price_item_sc</name>
   <tag></tag>
   <elementGuidId>329e0fc4-450e-4c26-9d8d-a8f387d0f8d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
