<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_phone_number</name>
   <tag></tag>
   <elementGuidId>a779d217-cdf3-4fbd-98b9-c13e571209e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[1]/div[4]/table/tbody/tr[3]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[1]/div[4]/table/tbody/tr[3]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
