<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_detail</name>
   <tag></tag>
   <elementGuidId>79c49902-6ddf-497b-bfe8-3b1f9f829a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[3]/div/div/div/div[2]/div/div/div[2]/div/div[1]/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[3]/div/div/div/div[2]/div/div/div[2]/div/div[1]/div[3]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
